import bbnData from "./Data/Data.js";
import "./Data/prototype/addComponent.js";
import "./Data/prototype/fixIndexes.js";
import "./Data/prototype/dataImpacted.js";
import "./Data/prototype/hasComponent.js";
import "./Data/prototype/hasParent.js";
import "./Data/prototype/isSame.js";
import "./Data/prototype/dataUpdate.js";
import "./Data/prototype/removeComponent.js";
import "./Data/prototype/setData.js";
import "./Data/prototype/unset.js";
import "./Data/static/addSequence.js";
import "./Data/static/getObject.js";
import "./Data/static/getValue.js";
import "./Data/static/propagate.js";
import "./Data/static/proxy.js";
import "./Data/static/proxyPop.js";
import "./Data/static/proxyPush.js";
import "./Data/static/proxyReverse.js";
import "./Data/static/proxyShift.js";
import "./Data/static/proxySort.js";
import "./Data/static/proxySplice.js";
import "./Data/static/proxyUnshift.js";
import "./Data/static/recognize.js";
import "./Data/static/startWatching.js";
import "./Data/static/stopWatching.js";
import "./Data/static/treatValue.js";

export default bbnData;
