import bbnProtoHtml from './Html/Proto.js';
import "./Html/prototype/connected.js";
import "./Html/prototype/create.js";
import "./Html/prototype/delete.js";
import "./Html/prototype/destroy.js";
import "./Html/prototype/emit.js";
import "./Html/prototype/forceUpdate.js";
import "./Html/prototype/get.js";
import "./Html/prototype/has.js";
import "./Html/prototype/hasSlots.js";
import "./Html/prototype/is.js";
import "./Html/prototype/isComponent.js";
import "./Html/prototype/isPropNative.js";
import "./Html/prototype/nextTick.js";
import "./Html/prototype/off.js";
import "./Html/prototype/on.js";
import "./Html/prototype/once.js";
import "./Html/prototype/position.js";
import "./Html/prototype/retrieveComponent.js";
import "./Html/prototype/retrieveElement.js";
import "./Html/prototype/retrieveNode.js";
import "./Html/prototype/retrieveSlotItems.js";
import "./Html/prototype/set.js";
import "./Html/prototype/tick.js";
import "./Html/prototype/treatValue.js";
import "./Html/prototype/watch.js";

export default bbnProtoHtml;